import tailwindAnimate from "tailwindcss-animate";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./layouts/**/*.{ts,tsx}",
    "./ui/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/styles/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: "var(--ff-poppins)",
        poppins: "var(--ff-poppins)",
      },
      fontSize: {
        "2xs": "10px",
        xs: "12px",
        sm: "14px",
        md: "16px",
        lg: "19px",
        xl: "23px",
        "2xl": "28px",
        "3xl": "33px",
        "4xl": "40px",
        "5xl": "48px",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary-800))",
          foreground: "hsl(var(--primary-foreground))",
          900: "hsl(var(--primary-900))",
          800: "hsl(var(--primary-800))",
          700: "hsl(var(--primary-700))",
          600: "hsl(var(--primary-600))",
          500: "hsl(var(--primary-500))",
          400: "hsl(var(--primary-400))",
          300: "hsl(var(--primary-300))",
          200: "hsl(var(--primary-200))",
          100: "hsl(var(--primary-100))",
          50: "hsl(var(--primary-50))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        complementary: {
          green: "hsl(var(--complementary-green))",
          "green-check": "hsl(var(--complementary-green-check))",
          yellow: "hsl(var(--complementary-yellow-05))",
          pink: "hsl(var(--complementary-pink))",
          blue: "hsl(var(--complementary-blue))",
          "blue-positive": "hsl(var(--complementary-blue-positive))",
          purple: "hsl(var(--complementary-purple))",
          red: "hsl(var(--complementary-red))",
          "red-negative": "hsl(var(--complementary-red-negative))",
          disable: "hsl(var(--complementary-disable))",
          black: "hsl(var(--complementary-black))",
          white: "hsl(var(--complementary-white))",
          "button-arrow": "hsl(var(--complementary-button-arrow))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        green: {
          DEFAULT: "hsl(var(--green-400))",
          900: "hsl(var(--green-900))",
          800: "hsl(var(--green-800))",
          700: "hsl(var(--green-700))",
          600: "hsl(var(--green-600))",
          500: "hsl(var(--green-500))",
          400: "hsl(var(--green-400))",
          300: "hsl(var(--green-300))",
          200: "hsl(var(--green-200))",
          100: "hsl(var(--green-100))",
          50: "hsl(var(--green-50))",
        },
        blue: {
          DEFAULT: "hsl(var(--blue-400))",
          900: "hsl(var(--blue-900))",
          800: "hsl(var(--blue-800))",
          700: "hsl(var(--blue-700))",
          600: "hsl(var(--blue-600))",
          500: "hsl(var(--blue-500))",
          400: "hsl(var(--blue-400))",
          300: "hsl(var(--blue-300))",
          200: "hsl(var(--blue-200))",
          100: "hsl(var(--blue-100))",
          50: "hsl(var(--blue-50))",
          dark: {
            DEFAULT: "hsl(var(--blue-dark-600))",
            600: "hsl(var(--blue-dark-600))",
            500: "hsl(var(--blue-dark-500))",
            200: "hsl(var(--blue-dark-200))",
          },
        },
        purple: {
          DEFAULT: "hsl(var(--purple-400))",
          900: "hsl(var(--purple-900))",
          800: "hsl(var(--purple-800))",
          700: "hsl(var(--purple-700))",
          600: "hsl(var(--purple-600))",
          500: "hsl(var(--purple-500))",
          400: "hsl(var(--purple-400))",
          300: "hsl(var(--purple-300))",
          200: "hsl(var(--purple-200))",
          100: "hsl(var(--purple-100))",
          50: "hsl(var(--purple-50))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [tailwindAnimate],
};
